[package]
name = "jr-license-server"
version = "0.1.0"
authors = ["dupp <dupp@wasu.com>"]
edition = "2018"

[dependencies]
actix-web = "3.1.0"
actix-service = "1.0.6"
actix-rt = "1.1.1"
env_logger = "0.7.1"
log = "0.4.11"
serde = "1.0.116"
serde_json = "1.0.58"
serde_derive = "1.0.116"
ring = "0.16.15"